### ISSUE TITLE
Request for Theme option for no background dark/ light

### ISSUE THREAD

**Issue by Nimai-HK** [sanoojes/Spicetify-Lucid#36]
This theme extracts images from the song covers and applies them as background with blur and darkening.

For lower-end PC users, Wish to see an option for no background, as this leads to heavy CPU usage.

*including well-demarcated UI elements for better accessibility.

**Comment by sanoojes** [comment]
there is an option for it in bloom settings `solid background ` also i will be rewriting the code and optimizing it for lower end pcs

**Comment by sanoojes** [comment]
![Uploading image.png…]()

**Comment by sanoojes** [comment]
hey @Nimai-HK can you check the theme now it should be solved

**Comment by Nimai-HK** [comment]
Yeah, Thanks!

**Comment by sanoojes** [comment]
hope you like it ❤️
