### ISSUE TITLE
[BUG] Transparent Window controls not scaling.

### ISSUE THREAD

**Issue by GildasEdraE** [sanoojes/Spicetify-Lucid#41]
### Do you have the latest versions of Spicetify, Spotify and Better Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Better Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.40.599.g606b7f29
- Installed from: Spotify Site
- Spicetify version: 2.36.13
- Color scheme:
- Extensions:
- Custom apps:
- Better Bloom installation method: PowerShell script
```

### Description

1. In Default Zoom, WIndows Control looks Normal
2. When Zooming Out, It's like hitting my Profile
3. When Zooming In, Blank Area is not filled by Window Control

### Screenshots

![Screenshot (205)](https://github.com/sanoojes/better-bloom/assets/89395504/9fbfa505-3ed6-4a01-8d21-de048960efd9)
Default Zoom

![Screenshot (204)](https://github.com/sanoojes/better-bloom/assets/89395504/013b1fe2-0676-44d9-867e-4f0e6f3ca694)
When Zoom Out

![Screenshot (206)](https://github.com/sanoojes/better-bloom/assets/89395504/36dea080-9251-4224-bd6d-673af47de933)
When Zoom In

**Comment by sanoojes** [comment]
zoom in and zoom out is currently under development !

**Comment by GildasEdraE** [comment]
> zoom in and zoom out is currently under development !

Thank you for answered, I hope Better Bloom gonna be best!

**Comment by GildasEdraE** [comment]
> zoom in and zoom out is currently under development !

Btw, can you tell me, if this issue done on GitHub or Discord(-Null-)?

**Comment by sanoojes** [comment]
Github but i prefer discord if are intersted in contributing tag me on discord !

**Comment by GildasEdraE** [comment]
> Github but i prefer discord if are intersted in contributing tag me on discord !

I'm Literally Already in your server and talk about "new name"🗿

**Comment by sanoojes** [comment]
bruh 😂 sorry

**Comment by GildasEdraE** [comment]
> bruh 😂 sorry

I forgive you😅, In Discord I'm as -Null- or gildasedraedrea9

**Comment by sanoojes** [comment]
okayy

**Comment by GildasEdraE** [comment]
> > zoom in and zoom out is currently under development !
> 
> Thank you for answered, I hope Better Bloom gonna be best!

*Lucid
