### ISSUE TITLE
UI suggestion for title bar

### ISSUE THREAD

**Issue by Jnss98b** [sanoojes/Spicetify-Lucid#44]
**Is your feature request related to a problem? Please describe.**
When the main pane is scrolled down, the title bar becomes brighter, which I understand as you're trying to convey layout hierarchy but it looks kinda bad with no padding at all to any of the panes. This is especially noticeable when playing songs with cover art using bright colors

**Describe the solution you'd like**
A very obvious and straightforward solution is to add some padding to the bottom of the title bar. Although I suggest removing the title bar brightening altogether as there's nothing scrolling under it, so there's no need to convey depth here.

**Additional context**
Default:
![image](https://github.com/sanoojes/Spicetify-Lucid/assets/24306400/99acc5aa-54e2-4dee-9098-b9054fb17b02)

Main pane scrolled:
![image](https://github.com/sanoojes/Spicetify-Lucid/assets/24306400/1841cea1-68a1-4cdf-ba49-43022f39d215)

**Comment by sanoojes** [comment]
oops sorry for the issue i didn't notice that because of the controls i will add a padding there

**Comment by sanoojes** [comment]
![image](https://github.com/sanoojes/Spicetify-Lucid/assets/93819264/baf0f04c-4a15-442a-b6e7-fe7009d02aae)
![image](https://github.com/sanoojes/Spicetify-Lucid/assets/93819264/a849c425-a65b-429d-a0c3-b50c6383856e)

i think there is enough padding there

**Comment by sanoojes** [comment]
and on the bottom its intentional as the window controls are transparent

**Comment by Jnss98b** [comment]
I was gonna report that one too but I was actually talking about this
![image](https://github.com/sanoojes/Spicetify-Lucid/assets/24306400/1e5241ce-137e-4231-9649-4dfa9682de37)

**Comment by Jnss98b** [comment]
Also play a song with a cover art with really bright colors and then scroll down to see what I mean by "title bar brightens when scrolled"

**Comment by sanoojes** [comment]
> I was gonna report that one too but I was actually talking about this ![image](https://private-user-images.githubusercontent.com/24306400/344443766-1e5241ce-137e-4231-9649-4dfa9682de37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MjMxMDEsIm5iZiI6MTcxOTcyMjgwMSwicGF0aCI6Ii8yNDMwNjQwMC8zNDQ0NDM3NjYtMWU1MjQxY2UtMTM3ZS00MjMxLTk2NDktNGRmYTk2ODJkZTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDA0NDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMDg2N2I2NDRhZWQ5MTNmYTk1YzNlOTU0ZDA4ZmQ3ODE1Y2YxZGZkM2E1YzFjMzQxZDRkNmQ2ZmQwYTBkNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MFFK5Qv4RKFMcht3CVnJey_0UgImPBKmhqHmfLo8bsU)

yes that was intentional there is some issues with some colors will try to add a fix for it

**Comment by sanoojes** [comment]
can you add a screenshot of the issue it will be much easier for me to check that

**Comment by sanoojes** [comment]
> Also play a song with a cover art with really bright colors and then scroll down to see what I mean by "title bar brightens when scrolled"

its not a brightness effect but a change in saturation i will fix that issue

**Comment by Jnss98b** [comment]
> can you add a screenshot of the issue it will be much easier for me to check that

I did in the original report

**Comment by Jnss98b** [comment]
Oh I was gonna do a screen recording but it seems like you fixed it already 😅

**Comment by sanoojes** [comment]
reverted the fix cause it has some issues with global nav
