### ISSUE TITLE
Add Rosé Pine colors

### ISSUE THREAD

**Issue by lichenophile** [sanoojes/Spicetify-Lucid#45]
I've made a preset for the [Rosé Pine](https://rosepinetheme.com/) Moon variant
```ini
[rosepine-moon]
main=232136
subtext=908caa
shadow=060606
text=e0def4
button=ea9a97
button-active=ea9a97
accent=c4a7e7
card=393552
sidebar=393552
```
![image](https://github.com/sanoojes/Spicetify-Lucid/assets/67679349/ab98c133-52e5-4019-8605-3c93a40ac375)

**Comment by sanoojes** [comment]
sure i will add it thanks for the contribution ❤️

**Comment by sanoojes** [comment]
instead of rosepine-moon am renaming it to rosepine
