### ISSUE TITLE
Discography page has too much padding at the top

### ISSUE THREAD

**Issue by Jnss98b** [sanoojes/Spicetify-Lucid#46]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.40.599.g606b7f29
- Installed from: Spotify site
- Spicetify version: 2.36.13
- Color scheme: darkgreen
- Extensions: None
- Custom apps: Lyrics Plus
- Lucid installation method: Spicetify Marketplace
```

### Description

1. Go to any artist page
2. Scroll down to the Discography section
3. Click on "Show all"
4. Notice the UI component containing the artist's name and filters is padded way too much

### Screenshots

https://github.com/sanoojes/Spicetify-Lucid/assets/24306400/b976d905-131d-4a60-84ba-7c8b1ef81b34

**Comment by sanoojes** [comment]
oops sorry to hear that i will fix it rn !

**Comment by Jnss98b** [comment]
I didn't notice it before but it seems like that bar isn't extending all the way to either side and also might have a different blur value or something that's causing the blur to look fragmented
![image](https://github.com/sanoojes/Spicetify-Lucid/assets/24306400/f917ff13-8035-45e1-9573-d44fa0a215c6)

https://github.com/sanoojes/Spicetify-Lucid/assets/24306400/734677a2-1c5d-473c-84d2-075cdca79455

**Comment by GildasEdraE** [comment]
> I didn't notice it before but it seems like that bar isn't extending all the way to either side and also might have a different blur value or something that's causing the blur to look fragmented ![image](https://private-user-images.githubusercontent.com/24306400/344872898-f917ff13-8035-45e1-9573-d44fa0a215c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTM5MjcsIm5iZiI6MTcxOTg5MzYyNywicGF0aCI6Ii8yNDMwNjQwMC8zNDQ4NzI4OTgtZjkxN2ZmMTMtODAzNS00NWUxLTk1NzMtZDQ0ZmEwYTIxNWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA0MTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjODdmYzc1OTAzMmJjZmMyNjk2NzMyYTExOTYzYmQzMTM1YzhkMWQ1M2U5OWIxNzBiZmZjMjNhYTdjMWQ4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VKTAkCzBfnllgnlpBJtwg1vEBiTwS-Z7jYeB488mNyI)
> 
>  20240702-0410-43.1153990.mp4

Not only bar, The song(title, and more) looks like didn't extending too

**Comment by GildasEdraE** [comment]
Because # and title looks little bit mis position

**Comment by sanoojes** [comment]
yes it is i will find a fix for that soon its because two of them are deferent elements
