### ISSUE TITLE
Page "What New"

### ISSUE THREAD

**Issue by vanja-san** [sanoojes/Spicetify-Lucid#48]
**Description**
A more compact view

**Alternative variation**
Add in "Lucid Settings"

**Additional context**

![изображение](https://github.com/sanoojes/Spicetify-Lucid/assets/7201687/d94b53a0-69b8-4cd4-8cdb-e6ad3fe604bc)
![изображение](https://github.com/sanoojes/Spicetify-Lucid/assets/7201687/ff8d0a11-b9f7-42ad-8f20-ddeba6fcb067)

**Comment by sanoojes** [comment]
hey ! thanks for the suggestion i will be adding it soon liked how it looks

**Comment by sanoojes** [comment]
check it out soory that i didnt reference this issue in the push https://github.com/sanoojes/Spicetify-Lucid/commit/27d03b2ba212b10615651c5ecb16494c46802924

It looks like this now 
![image](https://github.com/sanoojes/Spicetify-Lucid/assets/93819264/547247af-a1e1-4a88-91c0-a236462c6432)
