### ISSUE TITLE
Window Control Buttons do not blend in with the theme in full screen mode while using "Full Screen" extension by daksh2k

### ISSUE THREAD

**Issue by deb12378** [sanoojes/Spicetify-Lucid#49]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.41.434.g39a25e2c
- Installed from: Spotify site
- Spicetify version: v2.36.15
- Color scheme: Lucid / dark
- Extensions: adblock.js, fullScreenWrapper.js, theme.js
- Custom apps: lyrics-plus, new-releases, reddit
- Lucid installation method: PowerShell script
```

### Description

1. Install the extension "Full Screen" by daksh2k from the Marketplace.
2. Go into full screen using the new full screen button or by hitting the shortcut T or F.
3. Check the top right corner for the window control buttons.

The window controls should blend in like it does when not in full screen but it doesn't. 

### Screenshots

![Screenshot (136)](https://github.com/user-attachments/assets/3607c3d1-574a-4064-9e84-32d0f0cdf4be)

**Comment by sanoojes** [comment]
oops soory to cause an issue i will fix it right now !

**Comment by sanoojes** [comment]
can you update the theme and check if using marketplace just restart spotify and check @deb12378

**Comment by deb12378** [comment]
@sanoojes Thank you for such a prompt fix. It's exactly what was required. Just a little doubt, I can see that the controls are still there, it just isn't visible as it now blends in perfectly. I don't know if it will look good or not but what if the buttons were still visible but also blended with the background like it appears on the homepage like this. Attaching both the homepage and the full screen.
![image](https://github.com/user-attachments/assets/aee89586-1c4e-49f4-81f2-1100b574f488)

![image](https://github.com/user-attachments/assets/0e3ed00a-d790-4dd4-a552-ee00f4637ad1)

**Comment by sanoojes** [comment]
> @sanoojes Thank you for such a prompt fix. It's exactly what was required. Just a little doubt, I can see that the controls are still there, it just isn't visible as it now blends in perfectly. I don't know if it will look good or not but what if the buttons were still visible but also blended with the background like it appears on the homepage like this. Attaching both the homepage and the full screen. ![image](https://private-user-images.githubusercontent.com/70269983/349243251-aee89586-1c4e-49f4-81f2-1100b574f488.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTUxODIsIm5iZiI6MTcyMTE5NDg4MiwicGF0aCI6Ii83MDI2OTk4My8zNDkyNDMyNTEtYWVlODk1ODYtMWM0ZS00OWY0LTgxZjItMTEwMGI1NzRmNDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA1NDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZGRjMjdjNDJmMGQxNzJlMDBhZTIwMGFhMWYxZTFkNzIzZDM1NThjYThiYjc1N2I4NzljMThmNGNiODFhNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XhJS58WyUWkoPmGEyUaPAcuWdtFfag_vV0zygXDnla8)
> 
> ![image](https://private-user-images.githubusercontent.com/70269983/349242738-0e3ed00a-d790-4dd4-a552-ee00f4637ad1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTUxODIsIm5iZiI6MTcyMTE5NDg4MiwicGF0aCI6Ii83MDI2OTk4My8zNDkyNDI3MzgtMGUzZWQwMGEtZDc5MC00ZGQ0LWE1NTItZWUwMGY0NjM3YWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA1NDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMDJkZjdmNmMyZjljMWI5YzhlNDAyMjRkNzA5MWM5YzdhMTU1YTU3Mjk4Y2NhYWEzZTZlZTdhZGNkZDIyZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tTNDmA5MznDZvtskhDokjde4pEpa1uCw7XhbgBftoE8)

if the buttons were visible it will not be transparent we cant figure out that i will try to find a way to fix that soon 

full screen view in beautiful lyrics ![image](https://github.com/user-attachments/assets/4e9de4be-4b83-4b43-9647-b2238862e5d4)

cinema view in beautiful lyrics ![Screenshot 2024-07-17 111239](https://github.com/user-attachments/assets/4867838f-4536-4141-bdcb-0456f69cc73b)

window controls will not be transparent in this state

**Comment by sanoojes** [comment]
![image](https://github.com/user-attachments/assets/694c8d36-8cd1-440f-8158-77e27592d675)

do you mean something like this ? if yes its not from the theme i think you should make a issue on that extention requesting fullscreen with controls

**Comment by deb12378** [comment]
Yes I meant something like that only just that I wanted it to have only the symbols and not the rectangular boxes enclosing them. Like I wanted the ( -, 🗖, X) only and not the boxes enclosing them which cause it to be different from the background.

**Comment by deb12378** [comment]
> ![image](https://private-user-images.githubusercontent.com/93819264/349485791-694c8d36-8cd1-440f-8158-77e27592d675.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMzk3NzUsIm5iZiI6MTcyMTIzOTQ3NSwicGF0aCI6Ii85MzgxOTI2NC8zNDk0ODU3OTEtNjk0YzhkMzYtOGNkMS00NDBmLTgxNTgtNzdlMjc1OTJkNjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDE4MDQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNDRiZDMyODI2ODgxZThhYzkzMzFmZDJmMTUxZmQ3NDI3YjkyZmJjMDY5YmQyMzA3ZDdlYjFkN2FmZWRmMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cgjAjqJS5IeW6m3zMPljzSqsveiGJ3QCVKgKXZA72Vc)
> 
> do you mean something like this ? if yes its not from the theme i think you should make a issue on that extention requesting fullscreen with controls

Sure I'll just raise an issue with the full screen extension repo.

**Comment by deb12378** [comment]
Sure I'll just raise an issue with the full screen extension repo.
