### ISSUE TITLE
notification bug

### ISSUE THREAD

**Issue by elijahmary** [sanoojes/Spicetify-Lucid#51]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version:Spotify for Windows (64 bit) 1.2.42.290.g242057a2
- Installed from: Spotify site
- Spicetify version: v2.36.15
- Color scheme: dark
- Extensions: none 
- Custom apps: none
- Lucid installation method: Spicetify Marketplace
```

### Description

notificattion icon bug when you have unread notifications

### Screenshots

![image](https://github.com/user-attachments/assets/93dcafba-ec62-4abe-951c-81ac977ecc06)

**Comment by sanoojes** [comment]
oops i will fix it rn

**Comment by sanoojes** [comment]
sorry for the delay. 
i will fix it as soon as i can reproduce this
