### ISSUE TITLE
Background obfuscation even on artists with wide banner

### ISSUE THREAD

**Issue by Davoleo** [sanoojes/Spicetify-Lucid#55]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify for Windows (64 bit) 1.2.45.454.gc16ec9f6
- Installed from: Spotify site
- Spicetify v2.37.7
- Theme: Lucid / dark
- Extensions: webnowplaying.js, bookmark.js, popupLyrics.js, romaji.mjs, copytoclipboard.js, copy-save-images.js, shuffle+.js, volumePercentageWrapper.js, romaji_lyrics.js, SleepTimer.js, romaji-convert.js, adblock.js, beautiful-lyrics.mjs, theme.js
- Custom apps: marketplace, lyrics-plus, new-releases, ncs-visualizer
- Lucid installation method: Spicetify Marketplace
```

### Description

1. Open an artist page that has a wide background banner.
See the banner being blurry and having the starry effect.

I don't know if it's some weird stuff caused by marketplace, but I haven't been able to install it separately to test it via the PS1 script

### Screenshots

![image](https://github.com/user-attachments/assets/231cd1e7-d076-47de-bc2a-a4db20517aa1)

**Comment by sanoojes** [comment]
Sorry to hear that. Sometimes this can be caused by extensions or experimental features. Could you try disabling all extensions and resetting experimental features?

Preview of how it should look

![Screenshot 2024-09-04 165815](https://github.com/user-attachments/assets/c319d226-57ca-4f7b-966a-36836da3baf2)
![image](https://github.com/user-attachments/assets/ae4bac03-fed6-4b3f-8125-7b67f1d5d3ac)
![Screenshot 2024-09-04 165740](https://github.com/user-attachments/assets/d2b47298-d1ed-4b6c-a189-53aa20f24c57)

**Comment by Alex-666-666** [comment]
happens to me too

**Comment by sanoojes** [comment]
> happens to me too

oops i have no idea what is the problem here 💀

**Comment by sanoojes** [comment]
> happens to me too, tried what you said still doesnt work with no extensions

can you give me your about spotify 
![image](https://github.com/user-attachments/assets/f4dacdfc-286c-430c-b233-d6901fe1b233)

**Comment by Alex-666-666** [comment]
![image](https://github.com/user-attachments/assets/d4da7289-8357-4808-8439-fcc7b8d10786)

it annoys me bcs this is literally the perfect theme, just this issue and a small other one: the borders of playlists, songs and everything that small grey thing bcs they are rounded (i think i have ocd)

**Comment by sanoojes** [comment]
Using this snippet will remove all borders if you want
```css
:root{--border-thickness: 0px !important;}
```

for light borders
```css
:root{--border-thickness: var(--border-thickness) solid rgba(var(--spice-rgb-text), 0.05) !important;}
```

**Comment by sanoojes** [comment]
also i will add a quick fix rn !

**Comment by Alex-666-666** [comment]
ah no sorry i explained it wrong, i meant this: 
![Capture](https://github.com/user-attachments/assets/fa08a3a5-6a62-4a0f-83e3-282fc6652bfb)

**Comment by Alex-666-666** [comment]
its really small but there are small borders, most ppl wouldnt notice but it bugs me out and its a small visual bug

**Comment by sanoojes** [comment]
> ah no sorry i explained it wrong, i meant this: ![Capture](https://private-user-images.githubusercontent.com/173959407/364412216-fa08a3a5-6a62-4a0f-83e3-282fc6652bfb.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTk0MTAsIm5iZiI6MTcyNTQ1OTExMCwicGF0aCI6Ii8xNzM5NTk0MDcvMzY0NDEyMjE2LWZhMDhhM2E1LTZhNjItNGEwZi04M2UzLTI4MmZjNjY1MmJmYi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxNDExNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWM5ODg1MzZiOWY0MWE1Mzk1ZmQ4NzBiNjc2Mzc5MGI5YmY5YjM4ODhkNmJhOTQyNzdmZDg5MWNlYTgyMjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gfTGif1XxDuUE5ZBVfx5fBT3KFj54Qm0FaEXYbmzXGE)

Oh, thanks! I didn't even notice that. I'll fix those now, just give me a moment while I work on it.

**Comment by Alex-666-666** [comment]
and another thing i just noticed, i dont know if its intentional or not: 
![image](https://github.com/user-attachments/assets/7be0b7fb-26f3-4dfa-a318-87e4ac492d66)
![image](https://github.com/user-attachments/assets/366c5be0-7d79-40b2-896e-11edb722df4d)

the profile icon is hard to see, it depends on the skin i use, sometimes you barely can see it and sometimes a bit more but its still bad

**Comment by sanoojes** [comment]
> and another thing i just noticed, i dont know if its intentional or not: ![image](https://private-user-images.githubusercontent.com/173959407/364414831-7be0b7fb-26f3-4dfa-a318-87e4ac492d66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjMyMDYsIm5iZiI6MTcyNTQ2MjkwNiwicGF0aCI6Ii8xNzM5NTk0MDcvMzY0NDE0ODMxLTdiZTBiN2ZiLTI2ZjMtNGRmYS1hMzE4LTg3ZTRhYzQ5MmQ2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxNTE1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzlmNjFlYjJlNzZlY2Y5Yzc5ZDMxNWExYzhlMzY1ZTkwZmQyNzI5YWY2MmJiZjc0NzI4ZDE3OGQzODA4YmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NmI1KvZKyJyP85mIUNRqOU0NfVXlXOjxHrUe86VBioQ) ![image](https://private-user-images.githubusercontent.com/173959407/364415528-366c5be0-7d79-40b2-896e-11edb722df4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjMyMDYsIm5iZiI6MTcyNTQ2MjkwNiwicGF0aCI6Ii8xNzM5NTk0MDcvMzY0NDE1NTI4LTM2NmM1YmUwLTdkNzktNDBiMi04OTZlLTExZWRiNzIyZGY0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxNTE1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWE4YWI4ZDE0NWJkNjJhYzFjZmNmOGY1NjBjNWFlNmIwMGM0Mzk4N2E1MTFmODc2N2YxZDM4YjQyY2I4YmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kyflWEM6RIIeEmd9JdGiiG2sFGM3Fe5jcPI_HxVCnRo)
> 
> the profile icon is hard to see, it depends on the skin i use, sometimes you barely can see it and sometimes a bit more but its still bad, usually its like this: ![image](https://private-user-images.githubusercontent.com/173959407/364418356-9aaf9a5a-03d3-49c0-a8c1-32e13ffd78ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjMyMDYsIm5iZiI6MTcyNTQ2MjkwNiwicGF0aCI6Ii8xNzM5NTk0MDcvMzY0NDE4MzU2LTlhYWY5YTVhLTAzZDMtNDljMC1hOGMxLTMyZTEzZmZkNzhlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxNTE1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjIxN2MwMWQyYjYyOTBiZGVhZTc2NzZmODJmNzZhOTFmMjc3M2M3ODE3NGM5M2JlYzVmN2RlYWM5NGYxOWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QpkLlcjf51duBJ3-34YJn8NFPQKDzPhxUEv6_WhY3yA) maybe add an option if its intentional? ty

yes i will checkout that thats the issue with default profile

**Comment by sanoojes** [comment]
Fixed this issue.
Can you check if the issue is solved? @Davoleo @Alex-666-666

**Comment by Alex-666-666** [comment]
> Fixed this issue. Can you check if the issue is solved? @Davoleo @Alex-666-666

now i see the artist, and if i scroll down it gets more and more blurred the more i scroll down, it would be nice to add a option to always keep it unblurred. And sometimes the artist name and pic takes a bit to load but its prolly a spotify issue

**Comment by Davoleo** [comment]
sorry I haven't been able to follow the discussion;
Looks like the issue is fixed,
Artist wide banners now display correctly, I also like the blur transition! 
thanks for the quick fix & update
