### ISSUE TITLE
Small visual bug on connect to a device 

### ISSUE THREAD

**Issue by Alex-666-666** [sanoojes/Spicetify-Lucid#57]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: newest 
- Installed from: spotify site 
- Spicetify version: newest 
- Color scheme: happens with every color scheme 
- Extensions: auto skip vids, loopy loop, beautiful lyrics, hide podcasts, sleep timer, better spotifify genres 
- Custom apps: none
- Lucid installation method:powershell
```

### Description

a option is missing with compact and with default playbar

### Screenshots

![CaptuqqsXdQre](https://github.com/user-attachments/assets/2436217c-66c9-4382-afd8-0a94020c7f61)

**Comment by Alex-666-666** [comment]
normally: 
![image](https://github.com/user-attachments/assets/f57c8c71-be88-44f0-aeb0-79a67db299d7)

**Comment by sanoojes** [comment]
Fixed ! Theme will update soon.
