### ISSUE TITLE
[BUG] Shuffle and Repeat button not showing on playbar

### ISSUE THREAD

**Issue by mellasitus** [sanoojes/Spicetify-Lucid#59]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version:
- Installed from: (Windows Store, Spotify site, Flatpak, etc)
- Spicetify version:
- Color scheme:
- Extensions:
- Custom apps:
- Lucid installation method: (Spicetify Marketplace/PowerShell script/Bash script/Manual)
```

### Description

The shuffle button and loop play button are gone,

### Screenshots

![屏幕截图 2024-09-07 043406](https://github.com/user-attachments/assets/7b6380ac-06fe-4dc8-b769-6b57eeac3579)

**Comment by sanoojes** [comment]
This was a known issue for some of our users. I'm unable to reproduce it and am unsure of the root cause. We are working on a fix, so please be patient

**Comment by sanoojes** [comment]
can you provide your spotify spicetify version @mellasitus

**Comment by mellasitus** [comment]
Is this?
![屏幕截图 2024-09-07 175759](https://github.com/user-attachments/assets/bcdc68bb-4885-440f-a4fc-a6c6fe3eaebe)

**Comment by sanoojes** [comment]
Yes, I will check on that. What language are you using in Spotify?

**Comment by mellasitus** [comment]
usually Chinese

**Comment by sanoojes** [comment]
![image](https://github.com/user-attachments/assets/402c5f97-ad8f-4bdf-964d-e4d23e02ef55)

My guess was correct. It was an issue specific to some languages. I'll fix it as soon as possible.

**Comment by sanoojes** [comment]
> usually Simplified Chinese.But when i used English,it's right

yes i will update it soon

**Comment by mellasitus** [comment]
think

**Comment by mellasitus** [comment]
thank
