### ISSUE TITLE
where's the settings

### ISSUE THREAD

**Issue by mocca200** [sanoojes/Spicetify-Lucid#61]
i'm terribly sorry if i'm just being extremely stupid, but where are the lucid settings shown in the screenshots? i can't seem to find them anywhere and i've searched this repository for anything regarding the settings. thank you in advance

**Comment by sanoojes** [comment]
Spicetify does not currently support Spotify version 1.2.47. This incompatibility causes some context menu items to go missing. A fix is in progress and will be released soon; please wait for the update.

In the meantime, please consider downgrading to Spotify version 1.2.45. You can download the installer for Windows (64-bit) here:

https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.45.454.gc16ec9f6-122.exe

**Comment by sanoojes** [comment]
You can find other Spotify installation files, courtesy of amd64fox, in this spreadsheet: https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok

**Comment by mocca200** [comment]
i think it's compatible now actually, the settings button magically appeared today, thanks!

**Comment by sanoojes** [comment]
I fixed it yesterday added a button as fallback for now
