### ISSUE TITLE
[BUG] Top bar Position in Spotify 1.2.35

### ISSUE THREAD

**Issue by FraZyFPS** [sanoojes/Spicetify-Lucid#62]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.35.663
- Installed from: Spotify site
- Spicetify version: latest v2.38.2
- Color scheme: Dark
- Extensions: Full Screen, Lyric-plus
- Custom apps: -
- Lucid installation method: BOTH (Spicetify Marketplace & PowerShell script)
```

### Description

Padding-Top seems to be slightly off.

### Screenshots

![bug image](https://github.com/user-attachments/assets/113863f7-8b73-47f1-b9ba-405030b6947d)
![spotify file version](https://github.com/user-attachments/assets/dc4eaef1-284c-4d02-8bee-103dc1ca346e)

**Comment by sanoojes** [comment]
Ohh sorry to hear that but I currently don't support Spotify 1.2.35 can you try updating your Spotify?
