### ISSUE TITLE
Performance: Scroll Lag on Artist Page

### ISSUE THREAD

**Issue by kaer1a** [sanoojes/Spicetify-Lucid#63]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.47.364
- Installed from: Spotify site
- Spicetify version: 2.38.4
- Color scheme:
- Extensions: Adblockify, that' all
- Custom apps: Lyrics Plus
- Lucid installation method: Spicetify Marketplace
```

### Description

1. scrolling down are artist pages can either look fine or completely broken
2. on macOS this theme is incredibly unstable 

### Screenshots

![CleanShot 2024-10-07 at 22 58 18@2x](https://github.com/user-attachments/assets/012f0cee-ce16-4108-b09c-0235ab8f2818)

**Comment by sanoojes** [comment]
I'm sorry to hear that you're experiencing lag with the scroll implementation. Please check out the Lucid beta version to see if this issue has been resolved. I've implemented some optimizations that may improve performance.

**Comment by sanoojes** [comment]
@kaer1a Can you check the beta
