### ISSUE TITLE
Theme installation issue

### ISSUE THREAD

**Issue by ChrisVineyard-abc** [sanoojes/Spicetify-Lucid#65]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version:
- Installed from: (Windows Store, Spotify site, Flatpak, etc)
- Spicetify version:
- Color scheme:
- Extensions:
- Custom apps:
- Lucid installation method: (Spicetify Marketplace/PowerShell script/Bash script/Manual)
```

### Description

it worked fine yesterday, but now it's not work, even i didnt update anything.

i already uninstall and reinstall spotify and spicetify, but nothing work

**Comment by sanoojes** [comment]
Can you please provide more info of your installation method, Spotify and spicetify version?

**Comment by ChrisVineyard-abc** [comment]
Sorry for the late. im on Spotify v1.2.47 and Spicetify v2.38.4. it’s weird, i only have that problem on my laptop, but not on my PC. on my PC, Spotify crashes sometimes, but I just close it and everything works again. i mean it’s not stable when using the Lucid theme. Other themes don’t give me that problem, but im really fascinated by the Lucid theme. it’s very clean.

**Comment by ChrisVineyard-abc** [comment]
if no one else is complaining about that issue, then it might be just me. you should forget about it. anw, thank you for your support. 🙏

**Comment by sanoojes** [comment]
> Sorry for the late. im on Spotify v1.2.47 and Spicetify v2.38.4. it’s weird, i only have that problem on my laptop, but not on my PC. on my PC, Spotify crashes sometimes, but I just close it and everything works again. i mean it’s not stable when using the Lucid theme. Other themes don’t give me that problem, but im really fascinated by the Lucid theme. it’s very clean.

Oh, I think the issue might be with the installation. Could you try reinstalling Spotify, Spicetify, and the theme?

**Comment by sanoojes** [comment]
> if no one else is complaining about that issue, then it might be just me. you should forget about it. anw, thank you for your support. 🙏

Nah we can fix it.

**Comment by ChrisVineyard-abc** [comment]
ex: it work well until i restart my pc (* ￣︿￣)

**Comment by sanoojes** [comment]
> ex: it work well until i restart my pc (* ￣︿￣)

Ohh i think you have spotify from Microsoft Store 
do you ?

**Comment by ChrisVineyard-abc** [comment]
> can you give a screenshot of the installation of spicetify in terminal also which os are you in

sr i dont understand about "give a screenshot of the installation of spicetify in terminal" and im on windows 11 64bit 24h2

**Comment by sanoojes** [comment]
> > can you give a screenshot of the installation of spicetify in terminal also which os are you in
> 
> sr i dont understand about "give a screenshot of the installation of spicetify in terminal" and im on windows 11 64bit 24h2

nvm 
are you in Microsoft store version of Spotify ?

**Comment by ChrisVineyard-abc** [comment]
> > ex: it work well until i restart my pc (* ￣︿￣)
> 
> Ohh i think you have spotify from Microsoft Store do you ?
i installed from exe from spotify's web

**Comment by ChrisVineyard-abc** [comment]
> > > can you give a screenshot of the installation of spicetify in terminal also which os are you in
> > 
> > 
> > sr i dont understand about "give a screenshot of the installation of spicetify in terminal" and im on windows 11 64bit 24h2
> 
> nvm are you in Microsoft store version of Spotify ?

i installed from exe from spotify's web

**Comment by sanoojes** [comment]
can you show your about spotify 
![image](https://github.com/user-attachments/assets/e7677c2f-a498-408c-90de-341ffa044405)

**Comment by ChrisVineyard-abc** [comment]
![image](https://github.com/user-attachments/assets/16ca5e06-6515-4cba-9831-9dbbaeeb3017)

**Comment by ChrisVineyard-abc** [comment]
ah, one more thing, my pc run on 23h2 and dont have that problem. Maybe 24h2 has the problem, not your theme

**Comment by sanoojes** [comment]
> ah, one more thing, my pc run on 23h2 and dont have that problem. Maybe 24h2 has the problem, not your theme
windows version should not be a issue here
am on 24h2

**Comment by sanoojes** [comment]
wait the about spotify shows the same for microsoft store version

![image](https://github.com/user-attachments/assets/34299d93-649a-45d9-b8bb-ef572fb5542d)

Can you try installing v1.2.48 
https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.48.405.gf2c48e6f-2022.exe

**Comment by ChrisVineyard-abc** [comment]
> wait the about spotify shows the same for microsoft store version
> 
> ![image](https://private-user-images.githubusercontent.com/93819264/378107638-34299d93-649a-45d9-b8bb-ef572fb5542d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTY5NjYsIm5iZiI6MTcyOTM1NjY2NiwicGF0aCI6Ii85MzgxOTI2NC8zNzgxMDc2MzgtMzQyOTlkOTMtNjQ5YS00NWQ5LWI4YmItZWY1NzJmYjU1NDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDE2NTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZDJkYTY4OGJjMzk4YWI0OWVmNzAzN2VkNjFkMWYzODI4NWFhNTk1MzdmOWE3NDUzZWE0MmMxY2U4MjJiMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dbVe0GytElsD1W0jksDNY-A1Ch_TdoqEynfPTn3CtSI)
> 
> Can you try installing v1.2.48 https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.48.405.gf2c48e6f-2022.exe

no way .. btw i will try with your .exe

![image](https://github.com/user-attachments/assets/2d1cdfcd-c081-4b30-839b-610aad3cf90f)

**Comment by sanoojes** [comment]
did it fix ?

**Comment by ChrisVineyard-abc** [comment]
I think im fine with your .exe, thank you for your support !!

**Comment by sanoojes** [comment]
great am closing this issue as its fixed.
