### ISSUE TITLE
Cannot drag Spotify window in album view

### ISSUE THREAD

**Issue by styxnanda** [sanoojes/Spicetify-Lucid#66]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.48.405.gf2c48e6f
- Installed from: Spotify Site
- Spicetify version: v2.38.4
- Color scheme: Lucid / dark
- Extensions: theme.js
- Custom apps: marketplace
- Lucid installation method: Spicetify Marketplace
```

## Overview
1. Cannot drag Spotify window inside album view. Only a very small area around the "..." menu can be used.
2. This happens only in album view (when opening an album).
3. I've tested it in other pages seemed to work fine. Draggable anywhere else.
4. This is my first time using both Spotify and Spicetify, so there should be no changes made yet from vanilla installation apart from few theme tweaks in the Lucid settings like changing the background style and view mode to card from compact.

## Visual Explanation
This is the area affected in the window
![Bug Lucid Drag Window](https://github.com/user-attachments/assets/b764e513-1b2d-4be6-bbb3-bbce8da569ae)

## GIF Demonstration
The GIF is compressed to save space, sorry for bad quality. I host it in another site because GitHub doesn't allow file size to be exceeding 10 MB.
![gif](https://s11.gifyu.com/images/SObG3.gif)
Link to GIF if it doesn't appear above: https://gifyu.com/image/SObG3

**Comment by styxnanda** [comment]
Oh just checked as well. If the sidebar is extended, it covers more area of the topbar.

![image](https://github.com/user-attachments/assets/9c0ef7b4-aaa2-444d-9a91-73cbe90c367a)

**Comment by sanoojes** [comment]
Hey, thanks for reporting this and providing accurate ways to reproduce it. I'm fixing it right now!

**Comment by sanoojes** [comment]
> Oh just checked as well. If the sidebar is extended, it covers more area of the topbar.
> 
> ![image](https://private-user-images.githubusercontent.com/109936851/377933541-9c0ef7b4-aaa2-444d-9a91-73cbe90c367a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjcwODMsIm5iZiI6MTcyOTI2Njc4MywicGF0aCI6Ii8xMDk5MzY4NTEvMzc3OTMzNTQxLTljMGVmN2I0LWFhYTItNDQ0ZC05YTkxLTczY2JlOTBjMzY3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxNTUzMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzc1ZjUzODA5NTU5M2NlNDU3N2VkM2JjZGJhYmIxNWYxODVlMDhhODllNzFhZGZjYmVkZmZiODg0OThhZDRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rZKZIJKAcm3VlN_1iHMdh1q2tVqyvC-7v4bekI9ukVU)

Ohh Let me check that

**Comment by styxnanda** [comment]
> Hey, thanks for reporting this and providing accurate ways to reproduce it. I'm fixing it right now!

No problem. I hope it's easy to fix :D Good luck!

**Comment by sanoojes** [comment]
> > Hey, thanks for reporting this and providing accurate ways to reproduce it. I'm fixing it right now!
> 
> No problem. I hope it's easy to fix :D Good luck!

I don't know why my fix is not working 
applying the `-webkit-app-region: drag;` does nothing to the global nav

**Comment by styxnanda** [comment]
I'll try the code tomorrow to help as well, quite sleepy currently 😄 Forking it now.

**Comment by sanoojes** [comment]
> I'll try the code tomorrow to help as well, quite sleepy currently 😄 Forking it now.

Ohh thanks a lot i think this issue is related to the new search card styles added in https://github.com/sanoojes/Spicetify-Lucid/commit/5a54d0d3908af6750863f87f6c6a51182aa2c692

**Comment by sanoojes** [comment]
I found the issue! It was with the `.main-topbar-container` element (the top bar in the attached image). The `-webkit-app-region: no-drag;` style, combined with the element's position overlapping the global navigation, was blocking the drag functionality. 

The fix was to translate the `.main-topbar-container` slightly higher. This resolves the drag issue.

I will be adding a smoother animation and including these fixes in the next update I'm working on.

**Comment by styxnanda** [comment]
> I found the issue! It was with the `.main-topbar-container` element (the top bar in the attached image). The `-webkit-app-region: no-drag;` style, combined with the element's position overlapping the global navigation, was blocking the drag functionality.
> 
> The fix was to translate the `.main-topbar-container` slightly higher. This resolves the drag issue.
> 
> I will be adding a smoother animation and including these fixes in the next update I'm working on.
> 
> ![image](https://private-user-images.githubusercontent.com/93819264/377950164-f7ecd2b1-25ac-4ab4-8692-1461b5491532.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMDAwMzksIm5iZiI6MTcyOTI5OTczOSwicGF0aCI6Ii85MzgxOTI2NC8zNzc5NTAxNjQtZjdlY2QyYjEtMjVhYy00YWI0LTg2OTItMTQ2MWI1NDkxNTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDAxMDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ZWQ4NWYxNDY0M2M0ZDc5OTE4MmYwMGNiYzhlMzkwYmU1NGMzNzNkNjI5ODZiNjIyZGJkYWM5MTM4NTdiYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gPXw0vSqwVyrttGqN8VVVNebWhKyGrdATbOYvh1QJPY)

I see. That makes a lot of sense. Nice catch! Thank you very much for pointing out the root cause and for fixing it.
