### ISSUE TITLE
Can't install the theme

### ISSUE THREAD

**Issue by stepersy** [sanoojes/Spicetify-Lucid#67]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.48.405.gf2c48e6f
- Installed from: Spotify Site
- Spicetify version: v2.38.4
- Color scheme:
- Extensions: Cover Ambience, Full Screen, WikiFly, Image Opener, Remove Connected Bar
- Custom apps: library, lyrics-plus, marketplace
- Lucid installation method: PowerShell script
```

### Description

Hello, today, after the last update of Spotify, Spicetify Lucid stopped working for me. I tried to update it (after having updated Spicetify) but nothing changed. So I uninstalled it (powershell method) and tried to reinstall it through the powershell. But I received this error. What's the problem?

### Screenshots

![image](https://github.com/user-attachments/assets/83541144-6d24-44aa-ac22-62a710b495b6)

**Comment by sanoojes** [comment]
Can you try again ?
also try using a vpn as the site maybe blocked

**Comment by stepersy** [comment]
Hello, in the end, I solved it by deleting the folder 'Lucid' in the Spicetify directory. Then I tried to install it again, but nothing changed. However, when I tried to update it, it worked. So, right now, everything's going well.

**Comment by sanoojes** [comment]
great to hear that 
am closing this issue as its fixed.
