### ISSUE TITLE
Setting Acces Position get bug

### ISSUE THREAD

**Issue by ChrisVineyard-abc** [sanoojes/Spicetify-Lucid#70]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version:
- Installed from: (Windows Store, Spotify site, Flatpak, etc)
- Spicetify version:
- Color scheme:
- Extensions:
- Custom apps:
- Lucid installation method: (Spicetify Marketplace/PowerShell script/Bash script/Manual)
```

### Description

when i change that option, it will create the new ones. btw, could you add a feature to auto-resize the song cover when the height of the playbar is changed?

### Screenshots

![image](https://github.com/user-attachments/assets/f82213dd-557e-44b8-8bd6-0646d902787a)

**Comment by sanoojes** [comment]
Oops, sorry for the issue! I will check this right now.

Also, an auto-resize feature can be added soon!

**Comment by ChrisVineyard-abc** [comment]
if you have the newest, so i think that reported before the new update was pushed out. i will check back when i get home. 🙏

**Comment by sanoojes** [comment]
sorry I think I updated the beta 
is it fixed right now ?

**Comment by ChrisVineyard-abc** [comment]
yes, it's fixed. 🙏 thank you so much
