### ISSUE TITLE
Play Button Appeared as a purple square

### ISSUE THREAD

**Issue by Awesome126** [sanoojes/Spicetify-Lucid#71]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.38.720.ga4a70a0e
- Installed from: Spotify site
- Spicetify version: v2.38.4
- Color scheme: cappucino-machiatto
- Extensions: 
- Custom apps: Trashbin, shuffle+
- Lucid installation method: Powershell
```

### Description

The play button in the playbar appears to be a purple square. It only occurs when stop but get back to the normal icon when I play the song. Guess the triangle icon of playing is having issue?

### Screenshots

Stopped:
![image](https://github.com/user-attachments/assets/e1b76b79-5ef7-4a54-a25e-4d42b7b0e53b)
Played:
![image](https://github.com/user-attachments/assets/75faf5d4-093c-4597-a625-8629d48e1032)

**Comment by Awesome126** [comment]
I've restarted my Spotify for a several times. And even restarting my PC. The issue still persists after a day. Any suggestions?

**Comment by sanoojes** [comment]
> I've restarted my Spotify for a several times. And even restarting my PC. The issue still persists after a day. Any suggestions?

Btw which language are you using in spotify ?
also check if the theme is updated

**Comment by Awesome126** [comment]
Hi sorry for late reply.
I am using English in spotify.
And the lucid version is the latest.
I tried deleting lucid and reinstall it via marketplace. The play button is still a purple square. 😢

**Comment by sanoojes** [comment]
which color scheme and custom extensions do you use ?

**Comment by sanoojes** [comment]
ohh sorry currently i don't support 1.2.38 that's the issue i will add classes for that version rn which will fix it

**Comment by sanoojes** [comment]
can you try to update spotify

**Comment by Awesome126** [comment]
Nice! Issue fixed.
Never noticed that I was using old version tbh 😂
Thank you for your time. Good theme indeed!

**Comment by sanoojes** [comment]
You're very welcome!
