### ISSUE TITLE
Full screen mode broken

### ISSUE THREAD

**Issue by HaftIsntHere** [sanoojes/Spicetify-Lucid#75]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version:Spotify for Windows (64 bit) 1.2.49.439.gfae492c7
- Installed from: (Windows Store, Spotify site, Flatpak, etc) spotify site
- Spicetify version:Spicetify v2.38.4
- Color scheme: default
- Extensions: volume precentage, beautiful lyrics, shuffle+
- Custom apps: none
- Lucid installation method: (Spicetify Marketplace/PowerShell script/Bash script/Manual) powershell script
```

### Description

When entering full screen mode it looks broken, just like in the pic.

### Screenshots

![image](https://github.com/user-attachments/assets/13bd1be8-433a-46aa-8357-60594332c95b)

**Comment by elpideus** [comment]
Strange... It is like this for me...

![image](https://github.com/user-attachments/assets/1110645c-0d52-4c81-afd9-8a2e6a42de50)
No Lyrics


![image](https://github.com/user-attachments/assets/0b76ffd0-2328-41cc-bef2-01cf54d6c87a)
With Lyrics

**Comment by sanoojes** [comment]
https://github.com/surfbryce/beautiful-lyrics/issues/954

this is the issue with the extension this will be fixed soon by the dev

**Comment by sanoojes** [comment]
> Strange... It is like this for me...
> 
> ![image](https://private-user-images.githubusercontent.com/81350144/382555992-1110645c-0d52-4c81-afd9-8a2e6a42de50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MjY1OTgsIm5iZiI6MTczMDYyNjI5OCwicGF0aCI6Ii84MTM1MDE0NC8zODI1NTU5OTItMTExMDY0NWMtMGQ1Mi00YzgxLWFmZDktOGEyZTZhNDJkZTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDA5MzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NjZiZmY3Mzg1YmU2NzlhZjBjZjgyODU0NTk1OGViMTNiODNkMDc4OTE5ZjU3OTZlNjAwNzAwYzE5NGM1MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HBJEgVUYf220bjnSZDjqEirkd_hozrcMNqzw9llNqNc) No Lyrics
> 
> ![image](https://private-user-images.githubusercontent.com/81350144/382556070-0b76ffd0-2328-41cc-bef2-01cf54d6c87a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MjY1OTgsIm5iZiI6MTczMDYyNjI5OCwicGF0aCI6Ii84MTM1MDE0NC8zODI1NTYwNzAtMGI3NmZmZDAtMjMyOC00MWNjLWJlZjItMDFjZjU0ZDZjODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDA5MzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZmEyZWQyOWY3MGMzNmFiOGRkZWQ3Zjc1YmRiYjEwY2Q4ZDRhM2JlMGFiYjA2M2U5OGM4NDYxM2I2YTE2M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EFjB4TwYQpzuLu-BcYLCd4jOCXyIWtOiBskUgWQOnR0) With Lyrics

yes i need to add the full screen styles soon it is default rn

**Comment by sanoojes** [comment]
made a quick fix for it 

```css
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
.BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
    position: relative;
}
```

**Comment by Mysticc28** [comment]
> made a quick fix for it add this snippet for now
> 
> ```css
> .BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
> .BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
>     position: relative;
> }
> ```

Thank you so much!! Finally a fix for this issue! BTW, also switched to your theme and it is amazing!

**Comment by OverTex667** [comment]
> made a quick fix for it add this snippet for now
> 
> ```css
> .BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
> .BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
>     position: relative;
> }
> ```

where i have to put this ?

**Comment by sanoojes** [comment]
> > made a quick fix for it add this snippet for now
> > ```css
> > .BeautifulLyricsPage.Fullscreen .Content .PlayPanel .SliderBar,
> > .BeautifulLyricsPage.Fullscreen .Content .PlayPanel .MediaSpace {
> >     position: relative;
> > }
> > ```
> 
> where i have to put this, and how ?

Marketplace => snippets => add css
