### ISSUE TITLE
Incompatable with "Dynamic Sidebar" snipets

### ISSUE THREAD

**Issue by DaiterGG** [sanoojes/Spicetify-Lucid#77]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Installed from: Spotify site
Spotify for Windows (32 bit)
1.2.49.439.gfae492c7
Spicetify v2.38.4
Theme: Lucid (Beta) / catppuccin-darkrose
Extensions: keyboardShortcut.js, bookmark.js, skipStats.js, fullAlbumDate.js, adblock.js, SleepTimer.js, noControls.js, quickQueue.js, section-marker.js, copytoclipboard.js, whatsThatGenre.js, find-duplicates.js, playback-bar-waveform.js, volumePercentage.js, track-trim.js, theme.js
Custom apps: visualizer, name-that-tune, marketplace
- Lucid installation method: Spicetify Marketplace
```

### Description

All sidebar spinets use higher z-index to stay on top of screen

### Screenshots

![2024-11-08 02_19_46-Geoxor - I'm Here](https://github.com/user-attachments/assets/84b7c608-3d9d-46d5-b138-f5245482e9aa)
![2024-11-08 02_19_34-Geoxor - I'm Here](https://github.com/user-attachments/assets/ae64d04a-bc65-4dba-8436-5a585f3d460c)
![2024-11-08 01_26_17-](https://github.com/user-attachments/assets/01fee0e8-2ebd-4f5a-901e-0bf5ee6fa6c1)

**Comment by sanoojes** [comment]
This might be caused by other snippets. Also, don't expect all snippets to work perfectly, as the theme applies different styling. However, the dynamic left sidebar snippet does work well with the theme.

**Comment by sanoojes** [comment]
https://github.com/user-attachments/assets/fcf6a984-6967-47bc-8cde-46fd1489789c

![Screenshot 2024-11-08 074441](https://github.com/user-attachments/assets/893f0b9b-df53-4c72-9a1a-e0d84a16669d)
