### ISSUE TITLE
Font not readable and lucid settings was gone 

### ISSUE THREAD

**Issue by jeybsss** [sanoojes/Spicetify-Lucid#78]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.45.454.gc16ec9f6
- Installed from: Spotify site
- Spicetify version: Spicetify v2.38.4
- Color scheme: all
- Extensions:
- Custom apps:
- Lucid installation method: Marketplace
```

### Description

Font not readable and lucid settings was gone 

### Screenshots

![image](https://github.com/user-attachments/assets/dc0ccbd8-faed-4a76-a4ec-78f15794e9bf)
![image](https://github.com/user-attachments/assets/c24ab10f-ab4d-41f5-aecc-c062db5b8ba7)

**Comment by jeybsss** [comment]
this bug also persists in the latest version

**Comment by sanoojes** [comment]
try updating spotify and `spicetify backup apply`

**Comment by sanoojes** [comment]
Also can you give your About spotify ?

Like this 
![image](https://github.com/user-attachments/assets/0bdc970f-b1c1-4ea7-b9cd-770bbe4e3174)

![image](https://github.com/user-attachments/assets/bcd1a659-2e0e-4dd3-86c5-81e9e6cfd76a)

make sure its expanded

**Comment by jeybsss** [comment]
just finished updating and applying spicetify backup apply 
![image](https://github.com/user-attachments/assets/174ffa55-fd72-4dbb-9578-f863dd791e35)

**Comment by sanoojes** [comment]
are you using any custom snippets ?

**Comment by sanoojes** [comment]
can you run `spicetify enable-devtools` in terminal 
and reopen spotify then right click => inspect => navigate to console tab 
give a screenshot of console

**Comment by jeybsss** [comment]
> are you using any custom snippets ?

I'm using the new hover panel and pointer snippet, but the bug still persists even though the first thing i installed in the marketplace was the theme itself

**Comment by jeybsss** [comment]
> can you run `spicetify enable-devtools` in terminal and reopen spotify then right click => inspect => navigate to console tab give a screenshot of console
> 
> ![image](https://private-user-images.githubusercontent.com/93819264/384576140-67d2baa9-8151-443e-8008-a3b4e2808e62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMjU0MTAsIm5iZiI6MTczMTEyNTExMCwicGF0aCI6Ii85MzgxOTI2NC8zODQ1NzYxNDAtNjdkMmJhYTktODE1MS00NDNlLTgwMDgtYTNiNGUyODA4ZTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA0MDUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3M2JlYjUwYmFkODZlNTRlN2NmYTYwODk2MWUxZWNjODRhNjZhOGNhN2M1MDM5NzIzOGVhZDlhNzUwMTU5ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u9vPsgG4ny2T-rLWRNYj5b3ygVdSy_fT1Tz8gxDhqMI)

![image](https://github.com/user-attachments/assets/16ae08bc-3def-4011-a1d7-17966c1b3ce3)

**Comment by sanoojes** [comment]
> > can you run `spicetify enable-devtools` in terminal and reopen spotify then right click => inspect => navigate to console tab give a screenshot of console
> > ![image](https://private-user-images.githubusercontent.com/93819264/384576140-67d2baa9-8151-443e-8008-a3b4e2808e62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMjU0MTAsIm5iZiI6MTczMTEyNTExMCwicGF0aCI6Ii85MzgxOTI2NC8zODQ1NzYxNDAtNjdkMmJhYTktODE1MS00NDNlLTgwMDgtYTNiNGUyODA4ZTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA0MDUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3M2JlYjUwYmFkODZlNTRlN2NmYTYwODk2MWUxZWNjODRhNjZhOGNhN2M1MDM5NzIzOGVhZDlhNzUwMTU5ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u9vPsgG4ny2T-rLWRNYj5b3ygVdSy_fT1Tz8gxDhqMI)
> 
> ![image](https://private-user-images.githubusercontent.com/88224473/384576214-16ae08bc-3def-4011-a1d7-17966c1b3ce3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMjU1MTUsIm5iZiI6MTczMTEyNTIxNSwicGF0aCI6Ii84ODIyNDQ3My8zODQ1NzYyMTQtMTZhZTA4YmMtM2RlZi00MDExLWExZDctMTc5NjZjMWIzY2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA0MDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNTA1NjQwMjUzMTJiNDQ5NjczOTAyOGQ3ZTMzM2Y0NmMxMzJiY2FjNGNhZmIwYzNmMjgxZmUwMGU4ZDExN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.17oJ-FMuuGZ9IUinwt7hWkfJ25NFu5nKtm6f1JCNgzs)

Ohh i think this is the issue caused by settings can you clear the settings 

go to application tab => search `lucid`
delete `lucid-settings`  and reload spotify
![image](https://github.com/user-attachments/assets/dad7fdd7-94e1-494a-90c9-b5e118fb5af5)

**Comment by jeybsss** [comment]
Thanks the font is now back to normal and the lucid settings is now back, will close this request now.
