### ISSUE TITLE
Cannot Set Control Height in Spotify Newest version 

### ISSUE THREAD

**Issue by GildasEdraE** [sanoojes/Spicetify-Lucid#80]

**Comment by sanoojes** [comment]
yes this is a known issue i will checkout that rn

**Comment by GildasEdraE** [comment]
> yes this is a known issue i will checkout that rn
I reported this issue in github first, but you more frequently online, so I reported it in discord🗿

**Comment by sanoojes** [comment]
fixed it https://github.com/sanoojes/Spicetify-Lucid/commit/94a73280e5c313e4875acd8629ecffe0d4ae7105#diff-6f224bf0de2d1c1bd10903ac83481d3874e9f38927b1c04574cf1286f4794561

**Comment by GildasEdraE** [comment]
> fixed it [94a7328#diff-6f224bf0de2d1c1bd10903ac83481d3874e9f38927b1c04574cf1286f4794561](https://github.com/sanoojes/Spicetify-Lucid/commit/94a73280e5c313e4875acd8629ecffe0d4ae7105#diff-6f224bf0de2d1c1bd10903ac83481d3874e9f38927b1c04574cf1286f4794561)

Thank you!
