### ISSUE TITLE
Install Script broken

### ISSUE THREAD

**Issue by delasource** [sanoojes/Spicetify-Lucid#81]
### Do you have the latest versions of Spicetify, Spotify and Lucid?

- [X] I'm using the latest versions of Spicetify, Spotify and Lucid

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
curl -fsSL https://raw.githubusercontent.com/sanoojes/Spicetify-Lucid/main/install/install.sh | sh
```

### Description

There is a small typo in the install.sh script, that prevents it from being installed on MacOS. 

The variable definition
```
theme_url="https://raw.githubusercontent.com/sanoojes/Spicetify-Lucid/main/src/"
```
ends with a slash, yet below there will be another slash added to the string resulting in urls like 
```
https://raw.githubusercontent.com/sanoojes/Spicetify-Lucid/main/src//theme.js
``` 
which curl (on MacOs only?) does not understand

![CleanShot_2024-11-26_121207](https://github.com/user-attachments/assets/1d3a69e0-2588-4f98-952b-56a20598013a)

**Comment by sanoojes** [comment]
ohh sorry for the issue I didn't notice that am adding a fix rn 
also curl is available on mac right ?

**Comment by delasource** [comment]
yes. i simply had to download the script, edit it, remove one slash and it runs fine.

By the way, very cool theme and i like all the options!
