### ISSUE TITLE
Sleek theme, Powerfull functions.

### ISSUE THREAD

**Issue by SussyBob** [sanoojes/Spicetify-Lucid#82]
**Is your feature request related to a problem? Please describe.**
Your creation it's simply just a pure perfections for my aesthetics. It doesn't bother me if i need to click the library to expand it (so it's not related to any problem). But, wouldn't it be nicer when mouse pointer trigger open the sidebar smoothly? [this](https://github.com/jeroentvb/spicetify-playlist-icons) will also looks great if intergerated into your theme, the extension is no longer work in the latest update, something needs to be changed..

**Describe the solution you'd like**
Auto collapse/expand sidebar & control panel when mouse pointer runs over it.

**Additional context**
Someone has created Hover Panels but it's a little bit _Buggy_, heres's its CSS code:
```css

``` .Root__nav-bar {
  position: absolute;
  width: 35px;
  opacity: 0;
  bottom: 0;
  left: 0;
  top: 0;
  z-index: 12;
  transition: width 400ms, opacity 250ms ease-out;
}
.main-yourLibraryX-entryPoints {
  background: var(--spice-sidebar);
}
.Root__nav-bar:hover {
  width: 250px;
  opacity: 1;
  transition: width 250ms, opacity 400ms ease-in;
}
.LayoutResizer__resize-bar {
  cursor: none;
}
.Root__top-bar {
  opacity: 0;
  transition: visibility 5s, opacity 1s linear;
}
.Root__top-bar:hover {
  transition-delay: 0.5s;
  opacity: 1;
  transition: visibility 5s, opacity 0.5s linear;
}
.main-topBar-container {
  -webkit-padding-end: 32px;
  padding: 16px 85px;
  padding-inline-end: 32px;
  max-width: none;
}
.main-buddyFeed-container:hover {
  width: 350px !important;
  opacity: 1 !important;
  transition: width 250ms, opacity 400ms ease-in;
}
.main-buddyFeed-container {
  position: absolute;
  right: -5px;
  top: 0;
  bottom: 84px;
  width: 50px !important;
  opacity: 0 !important;
  transition: width 400ms, opacity 250ms ease-out;
}
.main-trackList-trackListHeader {
  top: 0 !important;
}
.main-yourLibraryX-navItem {
  overflow: hidden;
}
.main-coverSlotCollapsed-navAltContainer {
  overflow: visible;
}
.LayoutResizer__resize-bar {
  display: none;
}
:root {
  --left-sidebar-width: 35px !important;
  --right-sidebar-width: 50px !important;
  margin-left:-8px;
}

**Comment by SussyBob** [comment]
![image](https://github.com/user-attachments/assets/a8f2b711-31fd-431d-9c4d-cfb7dfc8e8a5)
make it match with the theme color.

**Comment by sanoojes** [comment]
Hey, I like your ideas for a collapsible sidebar and control panel. By the way, what do you mean by 'control panel'? Also, the playlist image feature is good. While the image feature is a valuable addition, it will introduce additional overhead.

**Comment by sanoojes** [comment]
> ![image](https://private-user-images.githubusercontent.com/95006470/391210508-a8f2b711-31fd-431d-9c4d-cfb7dfc8e8a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MzkwMDYsIm5iZiI6MTczMjkzODcwNiwicGF0aCI6Ii85NTAwNjQ3MC8zOTEyMTA1MDgtYThmMmI3MTEtMzFmZC00MzFkLTljNGQtY2ZiN2RmYzhlOGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDAzNTE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3OWNlZGNlYTllNDIxZTg1MmFjZjc2NzQ2ZWQyMmIzZjJlYjJlYzliMDdiODIyYmViZjhhMDk0NGY0YTI1OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IuNQbtmNLXkkLH4UmYB1tI4b94_PsroyYmUH37Akqh4) make it match with the theme color.

![image](https://github.com/user-attachments/assets/e136ea71-ae4a-4fff-9faa-bd76b55fbbd4)

that image is a webp file we need to change it to svg and change the color accordingly

**Comment by SussyBob** [comment]
> Hey, I like your ideas for a collapsible sidebar and control panel. By the way, what do you mean by 'control panel'? Also, the playlist image feature is good. While the image feature is a valuable addition, it will introduce additional overhead.

The panel on the right (queue, now playing view, connect to a device)

**Comment by SussyBob** [comment]
![image](https://github.com/user-attachments/assets/c312ce17-0b64-4253-ae44-1c2e9d451ea8)
 Playlist picture is a bit to the right, isn't it?
 
![image](https://github.com/user-attachments/assets/6e437418-8be3-4b08-afa7-aab59e523975)
And i also add tiny little bit of edge adjustment from "Rounded Buttons" snippet and its more matching for your theme i think. But, it doesn't apply to all buttons. And also some button has a weird clear edge like this:
![image](https://github.com/user-attachments/assets/29c8907d-9c93-4887-87c4-6bc170e87860)
(one (probably the only one) i noticed, hopefully you can see it)

**Comment by sanoojes** [comment]
oo I haven't noticed these I will fix those asap after my exams

**Comment by SussyBob** [comment]
alright, goodluck on your exams!

**Comment by Shockshwat** [comment]
@sanoojes is exam JEE by any chance?

**Comment by sanoojes** [comment]
Nope it's my +2 board exam

**Comment by sanoojes** [comment]
Am changing the theme build system rn I will add these features soon first in beta then main I will try to add these today or this before Sunday

**Comment by SussyBob** [comment]
greenscreen is 2x scarier than blue one ☠, it's ok i understand.

**Comment by sanoojes** [comment]
Nah idc about my data all important things are in cloud 😂 but I can't install windows rn 😭

**Comment by 5OBHAN** [comment]
boot disk issue it seems, is the disk not getting detected?

> ![IMG20241213060006.jpg](https://private-user-images.githubusercontent.com/93819264/395547112-4da66713-fd82-4ab7-8fb2-afb97d29bea8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMjQ3OTQsIm5iZiI6MTczNDMyNDQ5NCwicGF0aCI6Ii85MzgxOTI2NC8zOTU1NDcxMTItNGRhNjY3MTMtZmQ4Mi00YWI3LThmYjItYWZiOTdkMjliZWE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA0NDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5OTAxMDZiOTI1ZGIyNTAyZTg0OGZjMTRkZDlmMWFlZTVlMjJjYWRiZTJhOTE5MjdjMzdmMmFkYzhiN2VjZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2hgCC76qT8SY4VY9Gna0pQ21anaLcTRqg7iE1jTqRVw)
> 
> ![IMG-20241213-WA0015.jpeg](https://private-user-images.githubusercontent.com/93819264/395547116-f9424d88-314c-44ad-bb85-83bf80ba6974.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMjQ3OTQsIm5iZiI6MTczNDMyNDQ5NCwicGF0aCI6Ii85MzgxOTI2NC8zOTU1NDcxMTYtZjk0MjRkODgtMzE0Yy00NGFkLWJiODUtODNiZjgwYmE2OTc0LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwNDQ4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjZjZmMwZDZkOTRlNzE4ZWQ3NWFmY2RkNmIyZTgwOGM2YmMxOTMyYWU4YTFmMDA5ODkzOWMwZmNjNmNlNDBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IFTTmkzA2XvK0jdaTb_hzLAqdIrosDCiCHtUdZ4_Yvw)
> 
> Update 💀 I fckedup my lap need to reinstall os so it will be late

**Comment by sanoojes** [comment]
> boot disk issue it seems, is the disk not getting detected?

Yes I was unlucky as hell 😭 got 2 of my usb courrpt and kept trying i brought a new one and it's fixed now

**Comment by SussyBob** [comment]
thanks dude
